### ISSUE TITLE
Query: What is in the Custom F# compiler that differs from the open source one?

### ISSUE THREAD

**Issue by 7sharp9** [Lewix/fsharp-refactor#1]
I see there is a patch file for the compiler, I don't suppose you can annotate it so the changes have a context?

**Comment by Lewix** [comment]
Well the patch is based off this commit: https://github.com/tpetricek/fsharp/commit/0234eefe9b15fbae7e192a6f367575d39a53150c

What do you mean by annotating the patch? All it's really doing is moving some access modifiers around.

**Comment by 7sharp9** [comment]
I have created a fork of the F# compiler and consolidated all the custom compiler implementations (fsharp-refactor, fantomas, F# language binding).  This way we can keeping them all up to date with the main compiler.  

https://github.com/7sharp9/fsharpCompilerEditor

Going forward the output assembly name will be changed to FSharp.Compiler.Editor.dll.  

There will be a nuget packaged produced for easy usage from tools like fsharp-refactor, fantomas, and the F# Language binding.

**Comment by 7sharp9** [comment]
@Lewix Will you be developing this as a standalone tool or addin?  

Implementing this in the F# binding would be a welcome addition.

**Comment by Lewix** [comment]
I'm going to add it into the F# binding addin for MonoDevelop soon.

**Comment by 7sharp9** [comment]
Once the modified compiler is in place you should be able to reuse the parse results that are already produced and request a new parse when desired. 

I tried the monodevelop bit you have written last night but the untyped parse was not exposed in the compiler dll located in the lib folder.

**Comment by Lewix** [comment]
Yeah I had that problem too. I think that the FSharp.Compiler.dll is being loaded from the GAC instead of from the lib folder. Setting MONO_PATH to contain the lib folder fixed it for me.

What's happening with the modified compiler now? The repo you posted above has the changes to expose the parse tree I presume, but what else is needed to make sure an unmodified compiler.dll isn't loaded instead? I assume there's some metadata that has the name FSharp.Compiler which needs to be changed to FSharp.Compiler.Editing?

**Comment by 7sharp9** [comment]
The compiler at my branch has a different name and the metadata for the assembly name is different, this allows for a unique load at run time.  There's now a nuget package for this: [FSharp.Compiler.Editor](https://nuget.org/packages/FSharp.Compiler.Editor/)

**Comment by Lewix** [comment]
Thanks, I found the assembly and changed the references to use that instead.
